PACKAGE_NAME="rockchip-pwm-remotectl-rk35xx"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="rockchip_pwm_remotectl_rk35xx"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/rockchip-pwm-remotectl-rk35xx/1.0/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/rockchip-pwm-remotectl-rk35xx/1.0/build clean"
AUTOINSTALL="yes"
